#Hello World App Engine Config Script

application: aesthetic-fiber-789
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /.*
  script: fridgeSitterApp.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "latest"
- name: matplotlib
  version: "latest"